spring:
  application:
    name: backend

  output:
    ansi:
      enabled: always

  mongodb:
    auto-index-creation: true

  mail:
    host: ${ZENDR_SMTP_HOST}
    port: ${ZENDR_SMTP_PORT}
    username: ${ZENDR_SMTP_EMAIL}
    password: ${ZENDR_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #jackson:
    #serialization:
      #writeDatesAsTimestamps: false
  #devtools:
  #  restart:
  #    enabled: false
server:
  port: ${ZENDR_BACKEND_PORT}

logging:
  level:
    root: INFO