spring:
  application:
    name: backend

  output:
    ansi:
      enabled: always

  mongodb:
    uri: ${ZENDR_DB_URI}
    database: "test_db"
    auto-index-creation: true

  mail:
    host: ${ZENDR_SMTP_HOST}
    port: ${ZENDR_SMTP_PORT}
    username: ${ZENDR_SMTP_EMAIL}
    password: ${ZENDR_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${ZENDR_JWT_SECRET_KEY}
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

  tomtom:
    api-key: ${ZENDR_TOMTOM_API_KEY}

  openweather:
    api-key: ${ZENDR_OPENWEATHER_API_KEY}

  storage:
    endpoint: ${ZENDR_BUCKET_ENDPOINT}
    domain: ${ZENDR_BUCKET_DOMAIN}
    region: auto
    bucket: ${ZENDR_BUCKET_NAME}
    access-key: ${ZENDR_BUCKET_ACCESS_KEY}
    secret-key: ${ZENDR_BUCKET_SECRET_KEY}


  #jackson:
    #serialization:
      #writeDatesAsTimestamps: false
  #devtools:
  #  restart:
  #    enabled: false

server:
  port: ${ZENDR_BACKEND_PORT}

logging:
  level:
    root: INFO